services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017"
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    networks:
      app-network:
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
